# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/saisira/Documents/Video-Chunk-Compression

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/saisira/Documents/Video-Chunk-Compression

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/saisira/Documents/Video-Chunk-Compression/CMakeFiles /home/saisira/Documents/Video-Chunk-Compression//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/saisira/Documents/Video-Chunk-Compression/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Video-Scene-Change

# Build rule for target.
Video-Scene-Change: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Video-Scene-Change
.PHONY : Video-Scene-Change

# fast build rule for target.
Video-Scene-Change/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Video-Scene-Change.dir/build.make CMakeFiles/Video-Scene-Change.dir/build
.PHONY : Video-Scene-Change/fast

#=============================================================================
# Target rules for targets named Video-Chunking

# Build rule for target.
Video-Chunking: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Video-Chunking
.PHONY : Video-Chunking

# fast build rule for target.
Video-Chunking/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Video-Chunking.dir/build.make CMakeFiles/Video-Chunking.dir/build
.PHONY : Video-Chunking/fast

#=============================================================================
# Target rules for targets named video_quality_metrics

# Build rule for target.
video_quality_metrics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 video_quality_metrics
.PHONY : video_quality_metrics

# fast build rule for target.
video_quality_metrics/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_quality_metrics.dir/build.make CMakeFiles/video_quality_metrics.dir/build
.PHONY : video_quality_metrics/fast

#=============================================================================
# Target rules for targets named video_sizes

# Build rule for target.
video_sizes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 video_sizes
.PHONY : video_sizes

# fast build rule for target.
video_sizes/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_sizes.dir/build.make CMakeFiles/video_sizes.dir/build
.PHONY : video_sizes/fast

#=============================================================================
# Target rules for targets named video_frames

# Build rule for target.
video_frames: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 video_frames
.PHONY : video_frames

# fast build rule for target.
video_frames/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_frames.dir/build.make CMakeFiles/video_frames.dir/build
.PHONY : video_frames/fast

#=============================================================================
# Target rules for targets named compare_video

# Build rule for target.
compare_video: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compare_video
.PHONY : compare_video

# fast build rule for target.
compare_video/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compare_video.dir/build.make CMakeFiles/compare_video.dir/build
.PHONY : compare_video/fast

compare_video.o: compare_video.cpp.o
.PHONY : compare_video.o

# target to build an object file
compare_video.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compare_video.dir/build.make CMakeFiles/compare_video.dir/compare_video.cpp.o
.PHONY : compare_video.cpp.o

compare_video.i: compare_video.cpp.i
.PHONY : compare_video.i

# target to preprocess a source file
compare_video.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compare_video.dir/build.make CMakeFiles/compare_video.dir/compare_video.cpp.i
.PHONY : compare_video.cpp.i

compare_video.s: compare_video.cpp.s
.PHONY : compare_video.s

# target to generate assembly for a file
compare_video.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compare_video.dir/build.make CMakeFiles/compare_video.dir/compare_video.cpp.s
.PHONY : compare_video.cpp.s

scene_change.o: scene_change.cpp.o
.PHONY : scene_change.o

# target to build an object file
scene_change.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Video-Scene-Change.dir/build.make CMakeFiles/Video-Scene-Change.dir/scene_change.cpp.o
.PHONY : scene_change.cpp.o

scene_change.i: scene_change.cpp.i
.PHONY : scene_change.i

# target to preprocess a source file
scene_change.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Video-Scene-Change.dir/build.make CMakeFiles/Video-Scene-Change.dir/scene_change.cpp.i
.PHONY : scene_change.cpp.i

scene_change.s: scene_change.cpp.s
.PHONY : scene_change.s

# target to generate assembly for a file
scene_change.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Video-Scene-Change.dir/build.make CMakeFiles/Video-Scene-Change.dir/scene_change.cpp.s
.PHONY : scene_change.cpp.s

video_chunk.o: video_chunk.cpp.o
.PHONY : video_chunk.o

# target to build an object file
video_chunk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Video-Chunking.dir/build.make CMakeFiles/Video-Chunking.dir/video_chunk.cpp.o
.PHONY : video_chunk.cpp.o

video_chunk.i: video_chunk.cpp.i
.PHONY : video_chunk.i

# target to preprocess a source file
video_chunk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Video-Chunking.dir/build.make CMakeFiles/Video-Chunking.dir/video_chunk.cpp.i
.PHONY : video_chunk.cpp.i

video_chunk.s: video_chunk.cpp.s
.PHONY : video_chunk.s

# target to generate assembly for a file
video_chunk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Video-Chunking.dir/build.make CMakeFiles/Video-Chunking.dir/video_chunk.cpp.s
.PHONY : video_chunk.cpp.s

video_frames.o: video_frames.cpp.o
.PHONY : video_frames.o

# target to build an object file
video_frames.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_frames.dir/build.make CMakeFiles/video_frames.dir/video_frames.cpp.o
.PHONY : video_frames.cpp.o

video_frames.i: video_frames.cpp.i
.PHONY : video_frames.i

# target to preprocess a source file
video_frames.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_frames.dir/build.make CMakeFiles/video_frames.dir/video_frames.cpp.i
.PHONY : video_frames.cpp.i

video_frames.s: video_frames.cpp.s
.PHONY : video_frames.s

# target to generate assembly for a file
video_frames.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_frames.dir/build.make CMakeFiles/video_frames.dir/video_frames.cpp.s
.PHONY : video_frames.cpp.s

video_metrics.o: video_metrics.cpp.o
.PHONY : video_metrics.o

# target to build an object file
video_metrics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_quality_metrics.dir/build.make CMakeFiles/video_quality_metrics.dir/video_metrics.cpp.o
.PHONY : video_metrics.cpp.o

video_metrics.i: video_metrics.cpp.i
.PHONY : video_metrics.i

# target to preprocess a source file
video_metrics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_quality_metrics.dir/build.make CMakeFiles/video_quality_metrics.dir/video_metrics.cpp.i
.PHONY : video_metrics.cpp.i

video_metrics.s: video_metrics.cpp.s
.PHONY : video_metrics.s

# target to generate assembly for a file
video_metrics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_quality_metrics.dir/build.make CMakeFiles/video_quality_metrics.dir/video_metrics.cpp.s
.PHONY : video_metrics.cpp.s

video_sizes.o: video_sizes.cpp.o
.PHONY : video_sizes.o

# target to build an object file
video_sizes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_sizes.dir/build.make CMakeFiles/video_sizes.dir/video_sizes.cpp.o
.PHONY : video_sizes.cpp.o

video_sizes.i: video_sizes.cpp.i
.PHONY : video_sizes.i

# target to preprocess a source file
video_sizes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_sizes.dir/build.make CMakeFiles/video_sizes.dir/video_sizes.cpp.i
.PHONY : video_sizes.cpp.i

video_sizes.s: video_sizes.cpp.s
.PHONY : video_sizes.s

# target to generate assembly for a file
video_sizes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_sizes.dir/build.make CMakeFiles/video_sizes.dir/video_sizes.cpp.s
.PHONY : video_sizes.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Video-Chunking"
	@echo "... Video-Scene-Change"
	@echo "... compare_video"
	@echo "... video_frames"
	@echo "... video_quality_metrics"
	@echo "... video_sizes"
	@echo "... compare_video.o"
	@echo "... compare_video.i"
	@echo "... compare_video.s"
	@echo "... scene_change.o"
	@echo "... scene_change.i"
	@echo "... scene_change.s"
	@echo "... video_chunk.o"
	@echo "... video_chunk.i"
	@echo "... video_chunk.s"
	@echo "... video_frames.o"
	@echo "... video_frames.i"
	@echo "... video_frames.s"
	@echo "... video_metrics.o"
	@echo "... video_metrics.i"
	@echo "... video_metrics.s"
	@echo "... video_sizes.o"
	@echo "... video_sizes.i"
	@echo "... video_sizes.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

